language: groovy

jdk:
- oraclejdk7

before_script:
- "export DISPLAY=:99.0" 
- "sh -e /etc/init.d/xvfb start"

before_install:
- rm -rf ~/.gvm
- curl -s get.gvmtool.net > ~/install_gvm.sh
- chmod 775 ~/install_gvm.sh
- ~/install_gvm.sh
- echo sdkman_auto_answer=true > ~/.sdkman/etc/config
- source "/home/travis/.sdkman/bin/sdkman-init.sh"
<<<<<<< HEAD
- sdk install grails 2.1.5 
=======
- sdk install grails 2.1.4 
>>>>>>> 6ab03349cde6522d49cbe70516b785527b473582

branches:
  only:
    - master

<<<<<<< HEAD
script: grails -Dgeb.env=firefox test-app functional:cucumber --non-interactive --stacktrace

=======
script: grails -Dgeb.env=firefox test-app functional:cucumber --non-interactive --stacktrace
>>>>>>> 6ab03349cde6522d49cbe70516b785527b473582
